version: '3'
services:
  project:
    build: .
    image: photop/project-3:${IMAGE_TAG}
    ports:
     - "7000:7000"
    depends_on:
      - "mysql-db"

  mysql-db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=111111
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports: 
      - "5002:5002"
      
      
