version: '3'
services:
  project:
    build: .
    ports:
     - "5000:5000"

  mysql:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=111111
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports: 
      - "5002:5002"
  
