version: '3'
services:
  project:
    image: "echo IMAGE_TAG=123 > .env"
    build: .
    ports:
     - "8000:8000"

  redis:
    image: "redis:alpine"
    
  mysql:
    image: "pymysql:lastest"
    build: .
    ports:
    - "5000:5000"
  
