version: '3'
services:
  project:
    build: .
    ports:
     - "5005:5005"

  mysql-db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes: 
      - ./init:/docker-entrypoint-initdb.d
    ports: 
      - "5002:5002"
  
