version: '3'
services:
  project:
    build: .
    ports:
     - "5000:5000"

  redis:
    image: "redis:alpine"
    
  mysql:
    image: "pymysql:lastest"
    build: .
    ports:
    - "4000:4000"
  
