apiVersion: v2
kind: Service
metadata:
  name:  hello-python-service
spec:
  selector:
      app: hello-python3
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
      protocol: "TCP"
