apiVersion: v1
kind: Service
metadata:
  name:  hello-python-service
  labels:
    {{- include "lior.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: "TCP"
  selector:
    app: {{- include "lior.selectorLabels" . | nindent 4 }}
