apiVersion: v1
kind: Service
metadata:
  name:  hello-python-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: "TCP"
  selector:
      {{- include "lior.selectorLabels" . | nindent 4 }}
